### ISSUE TITLE
BUG: fhir_request.dart _makeRequest() for every RequestType is setted RequestType._delete

### ISSUE THREAD

**Issue by bobosette** [fhir-fli/fhir_at_rest#6]
Hi. First I wanna say thank u cause I'm working with fhir almost since 1 year and a half, and finally I find something for flutter. Your works will be extremely useful.
Maybe I found 1 bug and 1 thing to improve.

Today I was trying fhir and fhir_at_rest packages, and when I made a request I always got an exception. This is the code:

`
                   var newRequest = rest.FhirRequest.create(
                      base: Uri.parse('https://wbb.azurehealthcareapis.com'),
                      resource: newObs,
                    );

                    var response;

                    try {
                      response = await newRequest.request(headers: headers);
                    } catch (e) {
                      print(e);
                    }
`

I got mad for 1 hour and when i got through the debug I saw this in the fhir_request.dart file of fhir_at_rest package (from line 443 to 463):

`
Future<Map<String, dynamic>> _request(
    RestfulRequest type,
    String uri,
    Map<String, String> headers,
    String requestType, {
    Resource resource,
    String formData,
  }) async {
    try {
      final result = await _makeRequest(
          type: RestfulRequest.delete_ !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          thisRequest: uri,
          client: client,
          headers: headers,
          resource: resource == null ? null : resource.toJson());
      return result;
    } catch (e) {
      throw HttpException('Failed to complete a $requestType request, '
          '\nReturned exception: $e');
    }
  }
` 
The type of the request is always setted to RestfulRequest.delete_, and of course I tried to create an Observation so I got an exception.
When I changed the type of request with RestfulRequest.post_, everything worked fine.

And the thing to improve is that the response is a Map<String, dynamic>, so if there is some issues and call does't end with success an exception will always be thrown. Maybe you can handle this.

Thank u again.

**Comment by Dokotela** [comment]
Hey, thanks for the comments! I'm still trying to figure out the best way to perform some of these functions. I'm going to finish combining some of the packages in the next few days, and the restful requests will be part of them. I'll take another look at this problem then and see if it still has the problem.

**Comment by bobosette** [comment]
Thank u, perfect. Let me know. 
For now I have a fhir server with the micorsoft azure healthcare api  but I'm thinking about a switch to google cloud Healthcare api. 
I see u are working also on the authentication/roles on the server, aren't u?

**Comment by Dokotela** [comment]
Yeah, I'm not sure which is the best way to go. I've published the fhir_auth package to let people have something to work with, but I think that's the one that still needs the most work. I can get it to work with SMART on FHIR services (Hapi, Aidbox, etc). And I've connected to the google healthcare api too. I started to looking into azure and AWS Healthlake, but haven't gotten very far yet. For now I've decided to spend more time making it smoother with SMART on FHIR and Google (and looking into firebase too). Towards the bottom of this page, I started to document how to hookup a flutter app with Google Healthcare API, in case you wanted to look at it. https://www.fhirfli.dev/ And if you have anymore suggestions, they would be welcome, thanks!

**Comment by Dokotela** [comment]
Two more things.
1. I found what you meant in the restful request with it always being delete. So the next time I push to pub.dev that should be fixed.
2. Have you been able to authenticate to an azure healthcare api? If so, would you be willing to share how you did that? I'd like to try and include it in this package if you wouldn't mind.

**Comment by bobosette** [comment]
Ok perfect!!!
With Azure, yes I do. My configuration is:
- a fhir server with the azure healtcare api;
- authentication with azure directory and graph
- so before doing any call to the server, I do the login with Microsoft, I obtain an access token and then, also with your package fhir_at_rest, I can make calls putting in the request the access token as a header > Authentication: Bearer $accessToken

I hope is kind of comprehensible.

**Comment by Dokotela** [comment]
Makes sense. Would you be willing to share any of that code? (I understand if you're unable to due to copyright protections and the like). However, if you are, that would be great. And if that's the case, you're welcome to email me anything at grey@fhirfli.dev. Also though, if you do share anything, do at least one small pull request for https://github.com/fhir-fli/fhir_auth, so that you will be included as one of the package developers.

**Comment by bobosette** [comment]
Ok. I think I can share something, it is not a problem. Now I'm not on my
laptop, I will do as soon as I can

Il Lun 25 Gen 2021, 15:49 grey faulkenberry <notifications@github.com> ha
scritto:

**Comment by Dokotela** [comment]
Also, while it's not very active, we do have a growing slack channel for fhir-fli. I'm happy to invite you if you would be interested.

**Comment by Dokotela** [comment]
So I released the updated package, and the error should be corrected. Please give it a try and let me know if you still have issues.

**Comment by bobosette** [comment]
Ok perfect...i check

Il Mer 27 Gen 2021, 16:16 grey faulkenberry <notifications@github.com> ha
scritto:

**Comment by Dokotela** [comment]
Two more things then I'll stop bothering you (this is what you get when you open an issue, haha).
1. Here's our slack channel if you wanted to join: https://join.slack.com/t/fhir-fli/shared_invite/zt-kv1z4ahy-WbFYPh6Bn8YXN5cuscvS~g
2. If you get a chance to send me anything more about logging into azure, I would really appreciate it.

**Comment by bobosette** [comment]
Hi. I tried the updated package, it works perfectly. Great work. One thing about it: i saw that now the return value of request() is a resource. How can I handle the response if I have a 404 status?? On the fhirfli web sites I saw in the first example app that I could call 

response.fold((error) { }, (success) { }); 

but it doesn't work and I don't know why.

Sorry for the microsoft login, this week I was too busy, when I have a moment I'll give u the code.

For know I agree on your slack channel. Thank u

**Comment by Dokotela** [comment]
Sorry, yes. I changed it. I had been using [dartz](https://pub.dev/packages/dartz) for error handling. But that forced people into using the .fold method, and I wasn't sure if everyone would want to, so I returned back to just throwing an HttpException, and then letting you handle the error the way you'd like to. More recently I've been using [remotestate](https://pub.dev/packages/remote_state). But you could also use the classic:
```
try{
final response = await request.request();
print(response.toJson());
}catch(e){
print(e)
}
```
However, I'm open to requests. And if you'd prefer not to handle your own exceptions, I can look at changing it back.

**Comment by bobosette** [comment]
I usually use try/catch and I didn't know dartz and .fold() but I like it,
is a good way to handle especially httprequest response

Il Ven 29 Gen 2021, 22:06 grey faulkenberry <notifications@github.com> ha
scritto:

**Comment by Dokotela** [comment]
I had another idea about how to handle it. 
What if instead of an error or a dart/.fold(), I returned an OperationOutcome if there was an error?
That way it wouldn't freeze or crash the app if you don't catch the error, it would still return a resource, and then you could check if it's an OperationOutcome or not. Because if there's an error with your search from the server, it will also return an OperationOutcome.

For instance, in the public HAPI server, if I [search for a specific ID of a patient](http://hapi.fhir.org/baseR4/Observation/1245102/_history/1), but call it an observation, I get this response:
```
{
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "Resource with ID 1245102 exists but it is not of type Observation, found resource of type Patient"
  } ]
}
```
So if you had a 404 error or something, I could return:
```
{
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "error",
    "code": "404",
    "diagnostics": "Your search for $something resulted in an error, 404 Not Found"
  } ]
}
```
Or if there was a formatting error with one of your bundles:
```
{
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "error",
    "code": "formatError",
    "diagnostics": "A Transaction request was made, but no Bundle was included."
  } ]
}
```
I'd be interested to hear what you thought about this.

**Comment by bobosette** [comment]
Yes. It could be an idea. If the returned resource is an operation outcome
> handle the error. Sounds good

Il Lun 1 Feb 2021, 23:14 grey faulkenberry <notifications@github.com> ha
scritto:

**Comment by Dokotela** [comment]
Well, that's what I've done. I was looking through the FHIR spec, and one of the purposes of OperationOutcome is "When a RESTful interaction or operation fails", which seems to fit this purpose. So no more throwing Exceptions and no more folding. It will return a Resource, which is likely to be a Bundle or an OperationOutcome if there's an error. I'm going to close this, but if there's anymore issues, let me know!
